
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /wedding-template3/
url: crux-wedding.github.io


our-story:
  content-description: "The most obvious phyiscal phenomenon that is directly affected by the gravity of the moon are the tides of the ocean. The tides are an integral part of how maritime life is regulated and the comings and goings of the fishing world in coastal communities. But not very many people know that at certain times of the year when the orbits of the earth bring the sun and moon into right alignment."


# Build settings
markdown: kramdown
